vms:
  hosts:
    # https://portal-xaas-its.epfl.ch/automation/#/service/catalog/deployment/f8bcb113-9e53-4b61-9985-5a837e5add05?historyTab=true&requestId=d46a310e-7180-46a0-a47c-5935e83d277e
    itsblgwk0003.xaas.epfl.ch:
      inventory_deployment_stage: production
      ansible_python_interpreter: /usr/bin/python3.12
      ansible_user: root
