- name: Create PrometheusRule for Alerts
  kubernetes.core.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: "{{ app }}-alerts"
        namespace: "{{ openshift_namespace }}"
      spec:
        groups:
          - name: "{{ app }}-sync-alerts"
            rules:
              - alert: "{{ app }}SyncJobFailed"
                expr: >
                  kube_job_failed{namespace="{{ openshift_namespace }}", job_name="{{ app }}-sync"} > 0
                for: 5m
                labels:
                  severity: critical
                  sendto: telegram
                annotations:
                  summary: "{{ app }}-sync CronJob failed"
                  description: >-
                    The {{ app }}-sync CronJob has failed. Check logs for details.

              - alert: "{{ app }}SyncJobDidNotRun"
                expr: >
                  (hour() > 5 or hour() < 2) and
                  (time() - max(kube_job_status_start_time{namespace="{{ openshift_namespace }}", job_name=~"{{ app }}-sync.*"})) > 24 * 3600
                labels:
                  severity: warning
                  sendto: telegram
                annotations:
                  summary: "{{ app }}-sync didn't run in its scheduled window"
                  description: >-
                    The {{ app }}-sync CronJob didn't execute during its scheduled window (2h - 5h UTC).

              - alert: "{{ app }}SyncJobRunningTooLong"
                expr: >
                  time() - kube_job_status_start_time{namespace="{{ openshift_namespace }}", job_name="{{ app }}-sync"} > 3600
                for: 5m
                labels:
                  severity: critical
                  sendto: telegram
                annotations:
                  summary: "{{ app }}-sync running too long"
                  description: >-
                    The {{ app }}-sync CronJob has been running for more than 1 hour.

              - alert: "{{ app }}SyncContainerRestarting"
                expr: >
                  increase(kube_pod_container_status_restarts_total{namespace="{{ openshift_namespace }}", container="{{ app }}-sync"}[15m]) > 1
                for: 5m
                labels:
                  severity: warning
                  sendto: telegram
                annotations:
                  summary: "{{ app }}-sync container restarts detected"
                  description: >-
                    The container running {{ app }}-sync has restarted more than once in the last 15 minutes.

              - alert: "{{ app }}SyncJobCompletedButFailed"
                expr: >
                  kube_job_complete{namespace="{{ openshift_namespace }}", job_name="{{ app }}-sync"} == 1
                  and kube_job_failed{namespace="{{ openshift_namespace }}", job_name="{{ app }}-sync"} > 0
                for: 5m
                labels:
                  severity: warning
                  sendto: telegram
                annotations:
                  summary: "{{ app }}-sync completed but had failures"
                  description: >-
                    The {{ app }}-sync job completed but encountered failures. Check logs for details.

              - alert: "{{ app }}SyncPodRestartingTooOften"
                expr: >
                  increase(kube_pod_container_status_restarts_total{namespace="{{ openshift_namespace }}", pod=~"{{ app }}-sync-.*"}[30m]) > 3
                for: 5m
                labels:
                  severity: critical
                  sendto: telegram
                annotations:
                  summary: "{{ app }}-sync pod restarting too often"
                  description: >-
                    The {{ app }}-sync pod has restarted more than 3 times in the last 30 minutes.

          - name: "{{ app }}-alerts"
            rules:
              - alert: "{{ app }}PodRestartingTooOften"
                expr: >
                  increase(kube_pod_container_status_restarts_total{namespace="{{ openshift_namespace }}", pod=~"{{ app }}-.*"}[30m]) > 3
                for: 5m
                labels:
                  severity: critical
                  sendto: telegram
                annotations:
                  summary: "{{ app }} pod restarting too often"
                  description: >-
                    The {{ app }} pod has restarted more than 3 times in the last 30 minutes.

              - alert: "{{ app }}PodUnavailable"
                expr: >
                  kube_pod_status_ready{namespace="svc0070p-wikis",pod=~"outlinewiki-.*", condition="true"} == 0 unless on(pod) kube_pod_status_ready{namespace="svc0070p-wikis",pod=~"outlinewiki-(sync|redis).*"}
                for: 1m
                labels:
                  severity: critical
                  sendto: telegram
                annotations:
                  summary: "{{ app }} pod is not ready"
                  description: >-
                    The {{ app }} pod has been in an unready state (0/1) for over 1 minutes.

          - name: "{{ app }}-redis-alerts"
            rules:
              - alert: "{{ app }}RedisPodUnavailable"
                expr: >
                  kube_pod_status_ready{namespace="{{ openshift_namespace }}", pod=~"{{ app }}-redis-.*", condition="true"} == 0
                for: 1m
                labels:
                  severity: critical
                  sendto: telegram
                annotations:
                  summary: "{{ app }} Redis pod is not ready"
                  description: >-
                    The {{ app }} Redis pod has been in an unready state (0/1) for over 1 minutes.
