- name: Create Database in PostgreSQL Cluster
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: Database
      metadata:
        name: "{{ app.name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        cluster:
          name: postgres-cluster
        name: "{{ app.name + database.name_suffix }}"
        owner: "{{ app.name + database.user_suffix }}"
        passwordSecret:
          name: "{{ app.name }}-db-credentials"

- name: Create scheduled backup
  kubernetes.core.k8s:
    state: present
    definition:
      kind: ScheduledBackup
      apiVersion: postgresql.cnpg.io/v1
      metadata:
        name: "{{ app.name }}-scheduled-backup"
        namespace: "{{ openshift_namespace }}"
      spec:
        schedule: "0 0 2 * * *"
        backupOwnerReference: self
        cluster:
          name: postgres-cluster
