- name: Check if database secret exists
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ openshift_namespace }}"
    name: "{{ app.name }}-db-credentials"
  register: existing_db_secret

- name: Create database credentials secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app.name }}-db-credentials"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app.name }}"
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ app.name + database.user_suffix }}"
        password: "{{ secrets[env].database.password }}"
        database: "{{ app.name + database.name_suffix }}"

- name: Create application secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app.name }}-secrets"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        SECRET_KEY: "{{ secrets[env].secret_key }}"
        UTILS_SECRET: "{{ secrets[env].utils_secret }}"
        REDIS_URL: "{{ redis_url }}"
        DATABASE_URL: >-
          postgres://{{ app.name + database.user_suffix }}:{{ secrets[env].database.password }}@{{ database.host }}:5432/{{ app.name + database.name_suffix }}
        AZURE_CLIENT_ID: "{{ secrets[env].entra.client_id }}"
        AZURE_CLIENT_SECRET: "{{ secrets[env].entra.client_secret }}"
        AZURE_TENANT_ID: "{{ secrets[env].entra.tenant_id }}"
        SMTP_HOST: "{{ smtp.host }}"
        SMTP_PORT: "{{ smtp.port | string }}"
        SMTP_USERNAME: "{{ secrets[env].smtp.username }}"
        SMTP_PASSWORD: "{{ secrets[env].smtp.password }}"
        SMTP_FROM_EMAIL: "{{ secrets[env].smtp.from_email }}"
        SMTP_SECURE: "{{ smtp.secure }}"
        APP_NAME: "{{ app.display_name }} {{ '- Test' if env == 'test' else '' }}"
        FILE_STORAGE: "{{ file_storage.type }}"
        FILE_STORAGE_UPLOAD_MAX_SIZE: "{{ file_storage.max_upload_size | string }}"
