- name: Create BuildConfig for sync image
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: "{{ app }}-sync-build"
        namespace: "{{ openshift_namespace }}"
      spec:
        output:
          to:
            kind: ImageStreamTag
            name: "{{ app }}-sync:latest"
        source:
          git:
            uri: "{{ git_repo_url }}"
            ref: "main"
          contextDir: "roles/outline/files"
        strategy:
          dockerStrategy:
            dockerfilePath: Dockerfile
        triggers:
          - type: ConfigChange
          - type: ImageChange

- name: Create ImageStream for sync
  kubernetes.core.k8s:
    definition:
      apiVersion: image.openshift.io/v1
      kind: ImageStream
      metadata:
        name: "{{ app }}-sync"
        namespace: "{{ openshift_namespace }}"

- name: Start new build
  ansible.builtin.shell:
    cmd: "oc start-build {{ app }}-sync-build -n {{ openshift_namespace }} --follow"
  vars:
    ansible_become: false

- name: Create Sync CronJob
  kubernetes.core.k8s:
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: "{{ app }}-sync-cron"
        namespace: "{{ openshift_namespace }}"
      spec:
        schedule: "0 2 * * *"
        concurrencyPolicy: Forbid
        successfulJobsHistoryLimit: 3
        failedJobsHistoryLimit: 1
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - name: "{{ app }}-sync"
                    image: "{{ registry }}/{{ organisation }}/{{ app }}-sync:1.4.1"
                    imagePullPolicy: Always
                    envFrom:
                      - secretRef:
                          name: "{{ app }}-sync"
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                      limits:
                        cpu: 300m
                        memory: 512Mi
                restartPolicy: OnFailure
                imagePullSecrets:
                  - name: "{{ pull_secret_name }}"

- name: Ensure Sync Secret Exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-sync"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      data:
        OUTLINE_BASE_URL: "{{ ('https://' ~ subdomain ~ (env == 'test') | ternary('-test', '') ~ '.' ~ domain) | b64encode }}"
        OUTLINE_API_TOKEN: "{{ secrets[env].sync.outline_api_token | b64encode }}"
        EPFL_API_URL: "{{ secrets[env].sync.epfl_api_url | b64encode }}"
        EPFL_API_PASSWORD: "{{ secrets[env].sync.epfl_api_password | b64encode }}"
        EPFL_API_USERNAME: "{{ secrets[env].sync.epfl_api_username | b64encode }}"
