# These tasks are called handlers; they are only executed if
# “notified” at least once by another task in ../tasks
- name: _apache_needs_restart
  set_fact:
    _apache_needs_restart: true

- name: systemctl daemon-reload
  ansible.builtin.shell:
    cmd: systemctl daemon-reload

- name: _tomcat_needs_restart
  set_fact:
    _tomcat_needs_restart: true
