# Storage configuration
storage_class_name: wiki

# NFS configuration
nfs_provisioner:
  cpu_request: "100m"
  memory_request: "128Mi"

# PostgreSQL cluster configuration
postgres:
  instances: 2
  storage_size: "10Gi"
  superuser_access: true
  backup:
    enabled: true
    schedule: "0 0 2 * * *"
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"

# Secrets configuration
pull_secret_name: "svc0070-pull-secret"
