- name: Deploy NFS
  include_tasks:
    file: nfs.yml
    apply:
      tags:
        - cluster.nfs
  tags:
    - cluster.nfs

- name: Deploy PostgreSQL
  include_tasks:
    file: postgres.yml
    apply:
      tags:
        - cluster.postgres
  tags:
    - cluster.postgres

- name: Deploy Secrets
  include_tasks:
    file: secrets.yml
    apply:
      tags:
        - cluster.secrets
  tags:
    - cluster.secrets

- name: Deploy monitoring
  include_tasks:
    file: monitoring.yml
    apply:
      tags:
        - cluster.monitoring
  tags:
    - cluster.monitoring
