- name: Deploy NFS Subdir External Provisioner
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: nfs.epfl.ch/v1alpha1
      kind: NfsSubdirProvisioner
      metadata:
        name: "{{ storage_class_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        nfs:
          server: "{{ secrets[env].nfs.server }}"
          path: "{{ secrets[env].nfs.path }}"
        storageClass:
          defaultClass: false
          name: "{{ storage_class_name }}"
        resources:
          requests:
            cpu: "{{ nfs_provisioner.cpu_request }}"
            memory: "{{ nfs_provisioner.memory_request }}"
