- name: Deploy PostgreSQL cluster
  kubernetes.core.k8s:
      state: present
      definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
              name: postgres-cluster
              namespace: "{{ openshift_namespace }}"
          spec:
              backup:
                  barmanObjectStore:
                      destinationPath: "s3://{{ secrets[env].s3.url }}/{{ secrets[env].s3.name }}/postgresql-backup"
                      s3Credentials:
                          accessKeyId:
                              name: s3-credentials
                              key: ACCESS_KEY_ID
                          secretAccessKey:
                              name: s3-credentials
                              key: ACCESS_SECRET_KEY
              instances: 2
              storage:
                  size: "10Gi"
                  storageClass: "{{ storage_class_name }}"
              enableSuperuserAccess: true
              resources:
                  requests:
                      cpu: "500m"
                      memory: "1Gi"
              managed:
                  roles:
                      - name: outlinewiki-user
                        ensure: present
                        login: true
                        superuser: false
                        passwordSecret:
                            name: outlinewiki-db-credentials
