- name: Create Docker registry pull secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ pull_secret_name }}"
        namespace: "{{ openshift_namespace }}"
      data:
        .dockerconfigjson: "{{ secrets[env].puller }}"
      type: kubernetes.io/dockerconfigjson

- name: Create S3 credentials secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: s3-credentials
        namespace: "{{ openshift_namespace }}"
      stringData:
        AWS_BUCKET_NAME: "{{ secrets[env].s3.name }}"
        AWS_BUCKET_HOST: "{{ secrets[env].s3.host }}"
        AWS_ACCESS_KEY_ID: "{{ secrets[env].s3.access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ secrets[env].s3.access_key_secret }}"
      type: Opaque