- name: Create the pull secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ pull_secret_name}}"
        namespace: "{{ openshift_namespace }}"
      data:
        .dockerconfigjson: "{{ secrets[env].puller }}"
      type: kubernetes.io/dockerconfigjson
