registry: quay-its.epfl.ch
organisation: svc0070
image: outlinewiki
version: 0.82.5
app: outlinewiki
subdomain: collab
db_host: postgres-cluster-rw

storage_class: wiki
pull_secret_name: "{{ organisation }}-pull-secret"

git_repo_url: https://github.com/epfl-si/wiki.ops

secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_wiki/secrets/outline.yml') | from_yaml }}"

allowed_units:
  - DSI-EMP
  - DSI-GE
  - INVENTAIRE-CRI
  - ISAS-FSD
  - ISAS-GE
  - ISAS-GIF
  - ISCS-BA
  - ISCS-BI
  - ISCS-ERP
  - ISCS-GE
  - ISCS-IAM
  - ISGOV-BO
  - ISGOV-GE
  - ISGOV-ITSEC
  - ISGOV-PM
  - ITOP-GE
  - ITOP-INFR
  - ITOP-MWS
  - ITOP-SDDC
  - ITOP-SDESK
  - ITOP-WSRV
